services:
  - type: web
    name: tradingbuy-app
    env: node
    plan: standard
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://api.tradingbuy.net
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false

